### ISSUE TITLE
unhandled exception [rethinkdb dash]

### ISSUE THREAD

**Issue by tacyarg** [armenfilipetyan/express-session-rethinkdb#3]
Unhandled rejection TypeError: undefined is not a function
    at /var/www/csgobig.com/express/node_modules/express-session-rethinkdb/lib/express-session-rethinkdb.js:60:7
    at tryCatcher (/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate](/var/www/csgobig.com/express/node_modules/express-session-rethinkdb/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:358:17)
Unhandled rejection TypeError: undefined is not a function

**Comment by armenfilipetyan** [comment]
Will add function checking which should help resolve this issue.

**Comment by armenfilipetyan** [comment]
Type checking should be in place now for callback functions in version 0.1.3
